"""Run isolated economic backtest on six-TF Episodes.

Diagnostic only.  This runner consumes six-TF Episodes generated by the
connector, resolves outcomes on future M1 bars, and accounts explicit costs.
It never places orders, connects MT5, trains models, or changes can_trade.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backtest.economics import EconomicScenario
from backtest.sixtf_episode_backtest import (
    SixTFBacktestConfig,
    backtest_episodes,
    summarize_trades,
)
from engine.data_feed import load_frames
from engine.sixtf_marketobject_connector import SIX_TFS
from scripts.audit.run_sixtf_marketobject_connector import run_window


def _jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_jsonable(v) for v in value]
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return value


def _sha(value: Any) -> str:
    payload = json.dumps(_jsonable(value), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def run(
    *,
    data_dir: Path,
    start_time: str,
    end_time: str,
    decisions: int,
    step_minutes: int,
    output: Path,
    risk_pips: float,
    reward_r: float,
    horizon_m1_bars: int,
    spread_pips: float,
    slippage_pips: float,
    commission_per_lot_side: float,
) -> dict[str, Any]:
    out_dir = output.parent
    out_dir.mkdir(parents=True, exist_ok=True)
    window_path = out_dir / "sixtf_backtest_window_source.json"
    window = run_window(
        data_dir=data_dir,
        start_time=start_time,
        end_time=end_time,
        decisions=decisions,
        step_minutes=step_minutes,
        output=window_path,
        fast_backtest_mode=True,
    )
    # Load extra future M1 bars for outcome resolution.
    end_with_horizon = (
        pd.Timestamp(end_time, tz="UTC") + pd.Timedelta(minutes=max(1, horizon_m1_bars) + 5)
    ).isoformat()
    start_with_warmup = (pd.Timestamp(start_time, tz="UTC") - pd.Timedelta(days=90)).isoformat()
    frames = load_frames("EURUSD", SIX_TFS, data_dir=data_dir, start=start_with_warmup, end=end_with_horizon)
    economic_scenario = EconomicScenario(
        spread_pips=spread_pips,
        slippage_pips=slippage_pips,
        commission_per_lot_side=commission_per_lot_side,
    )
    backtest_config = SixTFBacktestConfig(
        risk_pips=risk_pips,
        reward_r=reward_r,
        horizon_m1_bars=horizon_m1_bars,
    )
    trades = backtest_episodes(
        window.get("episodes", []),
        frames["M1"],
        config=backtest_config,
        economics=economic_scenario,
    )
    summary = summarize_trades(trades)
    status = (
        "PASS_DIAGNOSTIC"
        if window.get("status") == "PASS"
        and window.get("window_gates", {}).get("full_prefix_all_pass") is True
        and summary["resolved_count"] > 0
        else "REVIEW"
    )
    report = {
        "artifact_kind": "SIXTF_EPISODE_ECONOMIC_BACKTEST_V1",
        "status": status,
        "source": str(data_dir),
        "period": {"start_time": start_time, "end_time": end_time},
        "decision_count": window.get("decision_count", 0),
        "episode_count": len(window.get("episodes", [])),
        "rejection_count": len(window.get("rejections", [])),
        "window_gates": window.get("window_gates", {}),
        "window_checksum": window.get("aggregates", {}).get("window_checksum"),
        "backtest_config": {
            "risk_pips": risk_pips,
            "reward_r": reward_r,
            "horizon_m1_bars": horizon_m1_bars,
            "entry_model": "M1_CLOSE_AT_DECISION_TIME",
            "outcome_model": "FIRST_TOUCH_SL_TP_ON_FUTURE_M1",
            "tie_policy": backtest_config.tie_policy,
        },
        "economic_scenario": {
            "spread_pips": spread_pips,
            "slippage_pips": slippage_pips,
            "commission_per_lot_side": commission_per_lot_side,
            "lot_size": economic_scenario.lot_size,
            "contract_size": economic_scenario.contract_size,
            "pip_size": economic_scenario.pip_size,
        },
        "policy": {
            "can_trade": False,
            "edge_claimed": False,
            "diagnostic_only": True,
            "fast_backtest_mode": True,
            "fast_backtest_mode_note": (
                "MTFNavigator context snapshot skipped per decision for economic "
                "throughput; six closed TF layers, MarketObjects, lineage, Episodes "
                "and FULL/PREFIX remain enforced."
            ),
            "mt5_connected": False,
            "orders_sent": False,
        },
        "summary": summary,
        "report_checksum": _sha({"summary": summary, "trades": trades}),
        "trades": trades,
    }
    output.write_text(json.dumps(_jsonable(report), indent=2, sort_keys=True), encoding="utf-8")
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=Path("data/raw/EURUSD"))
    parser.add_argument("--start-time", required=True)
    parser.add_argument("--end-time", required=True)
    parser.add_argument("--decisions", type=int, default=720)
    parser.add_argument("--step-minutes", type=int, default=60)
    parser.add_argument("--risk-pips", type=float, default=10.0)
    parser.add_argument("--reward-r", type=float, default=2.0)
    parser.add_argument("--horizon-m1-bars", type=int, default=240)
    parser.add_argument("--spread-pips", type=float, default=1.0)
    parser.add_argument("--slippage-pips", type=float, default=0.3)
    parser.add_argument("--commission-per-lot-side", type=float, default=5.0)
    parser.add_argument("--output", type=Path, default=Path("reports/audits/experiments/mission4/sixtf_episode_backtest.json"))
    args = parser.parse_args()
    report = run(
        data_dir=args.data_dir,
        start_time=args.start_time,
        end_time=args.end_time,
        decisions=args.decisions,
        step_minutes=args.step_minutes,
        output=args.output,
        risk_pips=args.risk_pips,
        reward_r=args.reward_r,
        horizon_m1_bars=args.horizon_m1_bars,
        spread_pips=args.spread_pips,
        slippage_pips=args.slippage_pips,
        commission_per_lot_side=args.commission_per_lot_side,
    )
    print(json.dumps(_jsonable({k: report[k] for k in ("status", "period", "decision_count", "episode_count", "summary", "policy")}), indent=2, sort_keys=True))
    return 0 if report["status"] in {"PASS_DIAGNOSTIC", "REVIEW"} else 1


if __name__ == "__main__":
    raise SystemExit(main())
